
export const questions = [
    {
      question: "¿A que se le da la patada?",
      resp_1: "A la lata",
      resp_2: "Al perro",
      resp_3: "Al gato",
      resp_4: "Al la suegra",
      correctAnswer: "A la lata",
      selectedAnswer: null,
    },
    {
      question: "Ño Fernanda... (Dibujos Animados)",
      resp_1: "Te pones de madre",
      resp_2: "Acabastes conmigo",
      resp_3: "Estas tufa",
      resp_4: "Apretastes",
      correctAnswer: "Estas tufa",
      selectedAnswer: null,
    },
    {
      question: "¿A que hora se tira el cañonazo en la Habana?",
      resp_1: "9:00 AM",
      resp_2: "8:00 PM",
      resp_3: "10:00 PM",
      resp_4: "9:00 PM",
      correctAnswer: "9:00 PM",
      selectedAnswer: null,
    },
    {
      question: "¿Cuál es el plato típico cubano por excelencia?",
      resp_1: "Ropa vieja",
      resp_2: "Congrí",
      resp_3: "Tostones",
      resp_4: "Lechón asado",
      correctAnswer: "Congrí",
      selectedAnswer: null,
    },
    {
      question: "¿Que es Cuba de las Antillas?",
      resp_1: "Una perla del mar",
      resp_2: "Una isla del golfo",
      resp_3: "La mayor de las Antillas",
      resp_4: "La llave de América",
      correctAnswer: "La mayor de las Antillas",
      selectedAnswer: null,
    },
    {
        question: "Paquito!... (Dibujos Animados)",
        resp_1: "Compadre",
        resp_2: "Fumiga",
        resp_3: "Parate",
        resp_4: "Apretastes",
        correctAnswer: "Fumiga",
        selectedAnswer: null,
      },
    {
      question: "¿Perro que ladra?",
      resp_1: "Tiene hambre",
      resp_2: "Despierta a los vecinos",
      resp_3: "Hace bulla",
      resp_4: "No muerde",
      correctAnswer: "No muerde",
      selectedAnswer: null,
    },
    {
      question: "¿Al pan con conserva de guayaba se le llama pan con _________?",
      resp_1: "azúcar",
      resp_2: "guayaba",
      resp_3: "timba",
      resp_4: "dulce",
      correctAnswer: "timba",
      selectedAnswer: null,
    },
    {
      question: "¿Que pierde el que va a Sevilla?",
      resp_1: "la silla",
      resp_2: "la cabeza",
      resp_3: "la dirección",
      resp_4: "la cordura",
      correctAnswer: "la silla",
      selectedAnswer: null,
    },
    {
      question: '¿Que le sigue a: "Al que Dios se lo dio"...?',
      resp_1: "Ganó la lotería",
      resp_2: "Que la suerte lo acompañe",
      resp_3: "San Pedro se lo bendiga",
      resp_4: "Que se llene de avaricia",
      correctAnswer: "San Pedro se lo bendiga",
      selectedAnswer: null,
    },
    {
      question: "¿\"Lo que esta pa' ti\". . .?",
      resp_1: "Alguien te lo quita",
      resp_2: "Nadie te lo quita",
      resp_3: "Está pa ti",
      resp_4: "La gente lo quiere",
      correctAnswer: "Nadie te lo quita",
      selectedAnswer: null,
    },
    {
      question: "Mientes... (Dibujos Animados)",
      resp_1: "Rata Inmunda",
      resp_2: "Eres un mentiroso",
      resp_3: "Descarado",
      resp_4: "Animal",
      correctAnswer: "Rata Inmunda",
      selectedAnswer: null,
    },
    {
      question: "¿El que hizo la ley, tambien que hizo?",
      resp_1: "La trampa",
      resp_2: "Las instituciones",
      resp_3: "Los deberes",
      resp_4: "Los derechos",
      correctAnswer: "La trampa",
      selectedAnswer: null,
    },
    {
      question: "¿Aunque la vistan de seda...?",
      resp_1: "Con la tela se quema",
      resp_2: "Los pañuelo ensucian",
      resp_3: "Mona se queda",
      resp_4: "Se va para la arboleda",
      correctAnswer: "Mona se queda",
      selectedAnswer: null,
    },
    {
      question: "¿Al mal tiempo...?",
      resp_1: "Mala lluvia",
      resp_2: "Buena cara",
      resp_3: "El sol se oculta",
      resp_4: "Vida mala",
      correctAnswer: "Buena cara",
      selectedAnswer: null,
    },
    {
        question: "¿Cuál es el deporte más popular en Cuba?",
        resp_1: "Béisbol",
        resp_2: "Fútbol",
        resp_3: "Boxeo",
        resp_4: "Atletismo",
        correctAnswer: "Béisbol",
        selectedAnswer: null,
      },
    {
      question: "¿Eramos pocos y...?",
      resp_1: "Pario Catana",
      resp_2: "La población aumenta",
      resp_3: "Llegó el familiar",
      resp_4: "Se fueron todos",
      correctAnswer: "Pario Catana",
      selectedAnswer: null,
    },
    {
      question: "¿\"Colorin, colorado. . .\"?",
      resp_1: "Un camino rebuscado",
      resp_2: "Mis deudas han aumentado",
      resp_3: "Un pescado a mi lado",
      resp_4: "Este cuento se ha acabado",
      correctAnswer: "Este cuento se ha acabado",
      selectedAnswer: null,
    },
    {
      question: "¿Que le paso a la cucarachita Maltina?",
      resp_1: "Alguien la regañó",
      resp_2: "Se hechó mucho perfume",
      resp_3: "Se encontró una moneda",
      resp_4: "Se comió una cebolla",
      correctAnswer: "Se encontró una moneda",
      selectedAnswer: null,
    },
    {
      question: "¿Árbol que nace torcido...?",
      resp_1: "Siempre se rompe",
      resp_2: "Un abono nunca le basta",
      resp_3: "El leñador se queda dormido",
      resp_4: "Jamás su tronco endereza",
      correctAnswer: "Jamás su tronco endereza",
      selectedAnswer: null,
    },
];